services:
  postgres:
    container_name: postgres
    image: postgres:15.5-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "5432:5432"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_INITIAL_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=keycloak
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - CONCIERGE_HOST=${WEB_HOST:-localhost}
      - CONCIERGE_PORT=${WEB_PORT:-15130}
    restart: unless-stopped
    volumes:
      - ./keycloak_import:/opt/keycloak/data/import
      - ./keycloak_javascript/concierge.jar:/opt/keycloak/providers/concierge.jar
    command: start-dev --import-realm --auto-build --features=scripts

volumes:
  postgres_data: