services:
  opensearch-node-base:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    restart: unless-stopped
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
  opensearch-node-disable-security:
    extends: opensearch-node-base
    environment:
      - "DISABLE_SECURITY_PLUGIN=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
  opensearch-node-enable-security:
    extends: opensearch-node-base
    environment:
      - "DISABLE_SECURITY_PLUGIN=false"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    volumes:
      - ${ROOT_CA}:/usr/share/opensearch/config/root-ca.pem
      - ${OPENSEARCH_ADMIN_CERT}:/usr/share/opensearch/config/admin.pem
      - ${OPENSEARCH_ADMIN_KEY}:/usr/share/opensearch/config/admin-key.pem
      - ${OPENSEARCH_NODE_CERT}:/usr/share/opensearch/config/node1.pem
      - ${OPENSEARCH_NODE_KEY}:/usr/share/opensearch/config/node1-key.pem
      - ./opensearch_config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./opensearch_config/opensearch-security/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - ./opensearch_config/opensearch-security/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ./opensearch_config/opensearch-security/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml

  opensearch-dashboards-base:
    image: opensearchproject/opensearch-dashboards:latest # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    restart: unless-stopped
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards 
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'  
  opensearch-dashboards-disable-security:
    extends: opensearch-dashboards-base
    environment:
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
  opensearch-dashboards-enable-security:
    extends: opensearch-dashboards-base
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch-node1:9200"]' # use https when security is enabled