[project]
name = "launch-concierge"
version = "0.5a12"
requires-python = ">=3.10"
dependencies = [
    "script-builder~=0.2a1"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"