version: '3.5'

services:
  ollama:
    extends:
      file: docker-compose-ollama.yml
      service: ollama
  opensearch-node1:
    extends:
      file: docker-compose-opensearch.yml
      service: opensearch-node1
  concierge:
    extends:
      file: docker-compose-concierge.yml
      service: concierge

volumes:
  opensearch-data1:

networks:
  default:
    name: concierge
