name: concierge

include:
  - ./concierge_packages/install_concierge/src/install_concierge/docker_compose/docker_compose_dependencies/docker-compose-keycloak.yml

networks:
  default:
    name: concierge