name: concierge

include:
  - ./docker-compose-dev.yml

services:
  concierge:
    extends:
      file: concierge_packages/launcher/src/launch_concierge/docker_compose/docker_compose_dependencies/docker-compose-concierge.yml
      service: ${CONCIERGE_SERVICE:-concierge}
    build:
      dockerfile: Dockerfile.local

networks:
  default:
    name: concierge
