[project]
name = "shabti-keycloak"
version = "0.1a2"
requires-python = ">=3.12"
dependencies = [
  "python-keycloak~=5.8.1"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"