[project]
name = "shabti-api-client"
version = "0.1a6"
requires-python = ">=3.12"
dependencies = [
  "httpx",
  "python-keycloak~=5.8.1",
  "shabti-types"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"