services:
  concierge:
    image: infosecinnovations/concierge
    container_name: concierge
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/file_uploads:/uploads
    environment:
      - OPENSEARCH_HOST=opensearch-node1
      - OLLAMA_HOST=ollama
    ports:
      - 8000:8000
    restart: unless-stopped