[project]
name = "launch-concierge"
version = "0.3.2"
requires-python = ">=3.12"
dependencies = [
    "script-builder"
]

[project.scripts]
install_concierge = "launch_concierge.install:install"
relaunch_concierge = "relaunch:relaunch"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"