name: concierge

include:
  - ./docker-compose-dev.yml

services:
  concierge-web:
    extends:
      file: ./docker_compose_dependencies/docker-compose-concierge.yml
      service: ${CONCIERGE_WEB_SERVICE:-concierge-web}
    build:
      context: ../../docker_containers/shabti_web
      additional_contexts: 
        python_packages: ../../python_packages
      dockerfile: Dockerfile.local

networks:
  default:
    name: concierge