services:
  zip:
    image: javieraviles/zip
    volumes:
      - ./policies:/input
      - ../shabti_configurator/docker_compose/docker_compose_dependencies/keycloak_javascript:/output
    command: sh -c "cd /input; zip -r /output/shabti.jar ."