name: concierge

include:
  - ./docker-compose-dev.yml

services:
  concierge_web:
    extends:
      file: ./docker_compose_dependencies/docker-compose-concierge.yml
      service: ${CONCIERGE_WEB_SERVICE:-concierge_web}
    build:
      context: ../../docker_containers/concierge_web
      dockerfile: Dockerfile.local

networks:
  default:
    name: concierge