name: concierge

include:
  - ./docker-compose-dev.yml

services:
  concierge:
    extends:
      file: ./docker_compose_dependencies/docker-compose-concierge.yml
      service: ${CONCIERGE_SERVICE:-concierge}
    build:
      context: ../../docker_containers/concierge_api
      additional_contexts: 
        python_packages: ../../python_packages
      dockerfile: Dockerfile.local

networks:
  default:
    name: concierge
