services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "5432:5432"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_INITIAL_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=keycloak
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/tls/cert.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/tls/key.pem
      - KC_HOSTNAME=${WEB_HOST:-localhost}
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC
      - SHABTI_HOST=${WEB_HOST:-localhost}
      - SHABTI_PORT=${WEB_PORT:-15130}
    restart: unless-stopped
    volumes:
      - ./keycloak_import:/opt/keycloak/data/import
      - ./keycloak_javascript/shabti.jar:/opt/keycloak/providers/shabti.jar
      - ${KEYCLOAK_CERT}:/opt/keycloak/tls/cert.pem
      - ${KEYCLOAK_CERT_KEY}:/opt/keycloak/tls/key.pem
    command: start --import-realm --auto-build --features=scripts

volumes:
  postgres_data: