[project]
name = "concierge-api-client"
version = "0.1a1"
requires-python = ">=3.12"
dependencies = [
  "httpx",
  "python-keycloak",
  "concierge-types"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"