name: Get Previous Release Assets

on:
  workflow_call:

jobs:
  get_assets:
    runs-on: [self-hosted, linux]
    steps:
      - name: Create directory for release files
        run: mkdir -p ./release_assets
      - name: Get current Windows release files  
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "shabti_win.zip"
          target: ./release_assets/shabti_win.zip
      - name: Get current Linux release files  
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "shabti_linux.zip"
          target: ./release_assets/shabti_linux.zip
      - name: Get current Mac release files  
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "shabti_mac.zip"
          target: ./release_assets/shabti_mac.zip

      - name: Unzip previous files
        run: |
          mkdir -p ./unzipped/win
          mkdir -p ./unzipped/linux
          mkdir -p ./unzipped/mac
          unzip -qq ./release_assets/shabti_win.zip -d ./unzipped/win
          unzip -qq ./release_assets/shabti_mac.zip -d ./unzipped/mac
          unzip -qq ./release_assets/shabti_linux.zip -d ./unzipped/linux