name: Publish Launcher

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v6
      - name: Install project
        run: bun install
      - name: Build Launcher Executable
        working-directory: ./shabti_configurator
        run: |
          bun run build_win
          bun run build_linux
          bun run build_mac

      # TODO: Code signing would go here

      - name: Get Launcher version
        id: package-version
        run: |
          PACKAGE_VERSION=$(cat ./shabti_configurator/package.json | jq '.version' | tr -d '"')
          echo "package_version: ${PACKAGE_VERSION}"
          echo "current-version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/get_previous_release_assets

      - name: Zip executables
        run: | 
          mkdir -p dist
          zip -j ./dist/shabti_win.zip ./shabti_configurator/dist/windows/shabti.exe ./unzipped/win/shabti_cli.exe
          zip -j ./dist/shabti_linux.zip ./shabti_configurator/dist/linux/shabti ./unzipped/linux/shabti_cli
          zip -j ./dist/shabti_mac.zip ./shabti_configurator/dist/mac/shabti ./unzipped/mac/shabti_cli
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.zip
          tag_name: shabti_launcher:${{steps.package-version.outputs.current-version}}
          target_commitish: ${{github.sha}}