name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Install Project
        run: bun install
      - name: Run Build Script
        env:
          TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
          NPM_CONFIG_TOKEN: ${{secrets.NPM_CONFIG_TOKEN}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        shell: bash
        run: bun run ./buildReleaseArtifacts.ts