name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v6
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install project
        run: bun install
      - name: Build Launcher Executable
        working-directory: ./shabti_configurator
        run: |
          bun run build_win
          bun run build_linux
          bun run build_mac

      # TODO: Code signing would go here

      - name: Get Launcher version
        id: package-version
        run: |
          PACKAGE_VERSION=$(cat ./shabti_configurator/package.json | jq '.version' | tr -d '"')
          echo "{current-version}={PACKAGE_VERSION}" >> $GITHUB_OUTPUT

      - name: Get Current Release Files  
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ".+\\.zip"
          regex: true

      - name: Unzip previous files
        run: |
          mkdir -p ./unzipped/win
          mkdir -p ./unzipped/linux
          mkdir -p ./unzipped/mac
          unzip -qq shabti_win.zip -d ./unzipped/win
          unzip -qq shabti_mac.zip -d ./unzipped/mac
          unzip -qq shabti_linux.zip -d ./unzipped/linux
      - name: Zip executables
        run: | 
          mkdir -p dist
          zip -j ./dist/shabti_win.zip ./shabti_configurator/dist/windows/shabti.exe ./unzipped/win/shabti_cli.exe
          zip -j ./dist/shabti_linux.zip ./shabti_configurator/dist/linux/shabti ./unzipped/linux/shabti_cli
          zip -j ./dist/shabti_mac.zip ./shabti_configurator/dist/mac/shabti ./unzipped/mac/shabti_cli
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.zip
          tag_name: shabti_launcher:${{steps.package-version.outputs.current-version}}
          target_commitish: ${{github.sha}}