name: Publish

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: "GitHub name for release"


jobs:
  publish:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v6
      - name: Install Project
        run: bun install
      - name: Run Build Script
        env:
          TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
          NPM_CONFIG_TOKEN: ${{secrets.NPM_CONFIG_TOKEN}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        shell: bash
        run: bun run ./buildReleaseArtifacts.ts
      # TODO: insert code signing here
      - name: Zip executables
        run: | 
          mkdir -p dist
          zip -j ./dist/shabti_win.zip ./shabti_configurator/dist/windows/shabti.exe ./shabti_cli/dist/windows/shabti_cli.exe
          zip -j ./dist/shabti_linux.zip ./shabti_configurator/dist/linux/shabti ./shabti_cli/dist/linux/shabti_cli
          zip -j ./dist/shabti_mac.zip ./shabti_configurator/dist/mac/shabti ./shabti_cli/dist/mac/shabti_cli
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.zip
          tag_name: ${{inputs.releaseName}}
          target_commitish: ${{github.sha}}